services:
  # --- BASE DE DONNÉES (ISOLÉE) ---
  ecoride_db:
    image: mysql:8.0
    container_name: ecoride_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ecoride_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecoride_backend_net # Uniquement accès au backend

  # --- PHPMYADMIN (PROTÉGÉ) ---
  #ecoride_pma:
  #  image: phpmyadmin:latest
  #  container_name: ecoride_pma
  #  restart: always
    # PORTS SUPPRIMÉS : Ne pas exposer sur le web en direct !
  #  environment:
  #    PMA_HOST: ecoride_db
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  # networks:
  #    - ecoride_backend_net

  # --- BACKEND (SYMFONY) ---
  symfony_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony_backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/var/www/html
      - ecoride_symfony_vendor_cache:/var/www/html/vendor
      - ecoride_symfony_var_cache:/var/www/html/var
      - ./frontend/uploads:/var/www/html/public/uploads
    networks:
      - ecoride_backend_net # Parle à la DB
      - ecoride_frontend_net # Parle au Nginx

  # --- FRONTEND (NGINX + CLOUDFLARE READY) ---
  ecoride_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecoride_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html
      - ./frontend/uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - symfony_backend
    networks:
      - ecoride_frontend_net
      # - web_proxy # Décommente ceci si tu as un réseau pour ton Proxy (NPM/Traefik)

networks:
  # Réseau ultra-privé : Aucune sortie internet possible pour la DB
  ecoride_backend_net:
    driver: bridge
    internal: true 
  
  # Réseau pour la communication web
  ecoride_frontend_net:
    driver: bridge

volumes:
  ecoride_db_data:
  ecoride_avatars_data:
  ecoride_symfony_vendor_cache:
  ecoride_symfony_var_cache: