# compose.yaml
# Version de la spécification Docker Compose
version: '3.8'

# Définition des services (conteneurs)
services:
  # Service pour la base de données MariaDB
  db:
    image: mariadb:10.6 # Utilise une image MariaDB stable
    environment:
      # Variables d'environnement MariaDB en dur
      MARIADB_ROOT_PASSWORD: fn7Osjk53LSMsa90 # Ton vrai mot de passe root MariaDB
      MYSQL_DATABASE: sf_ecoride
      MYSQL_USER: Flo466
      MYSQL_PASSWORD: njs86bJsv3K82
    ports:
      - "3306:3306" # Mappe le port 3306 du conteneur au port 3306 de l'hôte
    volumes:
      - db_data:/var/lib/mysql # Volume persistant pour les données de la base de données

  # Le service MongoDB est supprimé.

  # Service pour ton application PHP (le backend Symfony)
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BREAKER: ${RANDOM_STRING:-$(date +%s)} # Génère un timestamp unique à chaque build
    volumes:
      - .:/var/www/html # Monte ton répertoire de code local dans le conteneur PHP
      - php_socket:/var/run/php # Volume pour le socket FPM, partagé avec Nginx
    environment:
      # Variables d'environnement pour PHP en dur
      APP_ENV: dev
      APP_SECRET: 19fd7ad4073866297c5c7eb00317e383d558ca0dde041662837dd95d58e38341 # Ton vrai APP_SECRET

      DATABASE_URL: "mysql://Flo466:njs86bJsv3K82@db:3306/sf_ecoride?serverVersion=10.6&charset=utf8mb4&sslmode=DISABLED"
    depends_on:
      - db # Dépend seulement de MariaDB maintenant

  # Service pour le serveur web (Nginx)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - php_socket:/var/run/php
    depends_on:
      - php

# Déclaration des volumes persistants
volumes:
  db_data:
  mongodb_data: # Gardons cette déclaration de volume, elle ne fera pas de mal si elle n'est pas utilisée.
  php_socket:
