-- MySQL Script generated by MySQL Workbench
-- Sat May  3 19:37:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `photo` BLOB NULL DEFAULT NULL,
  `username` VARCHAR(50) NULL DEFAULT NULL,
  `credits` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `role_id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `label` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`));


-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX (`role_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`),
  CONSTRAINT ``
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`role_id`));


-- -----------------------------------------------------
-- Table `mydb`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NULL,
  `ratting` INT NULL,
  `status` VARCHAR(50) NULL,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_has_review` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_has_review` (
  `user_id` INT NOT NULL,
  `review_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `review_id`),
  INDEX `fk_user_has_review_review1_idx` (`review_id` ASC) VISIBLE,
  INDEX `fk_user_has_review_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_review_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_review_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `mydb`.`review` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(50) NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(50) NULL,
  `color` VARCHAR(50) NULL,
  `licence_plate` VARCHAR(50) NULL,
  `energy` VARCHAR(50) NULL,
  `first_registration_date` VARCHAR(50) NULL,
  `user_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  PRIMARY KEY (`car_id`),
  INDEX `fk_car_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_car_brand1_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_brand1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carpooling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carpooling` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carpooling` (
  `carpooling_id` INT NOT NULL AUTO_INCREMENT,
  `departure_date` DATE NULL,
  `departure_time` TIME NULL,
  `departure_place` VARCHAR(50) NULL,
  `arrival_date` DATE NULL,
  `arrival_time` TIME NULL,
  `arrival_place` VARCHAR(50) NULL,
  `status` VARCHAR(50) NULL,
  `seat_count` INT NULL,
  `price_per_person` FLOAT NULL,
  `is_eco` TINYINT NULL,
  `car_id` INT NOT NULL,
  PRIMARY KEY (`carpooling_id`),
  INDEX `fk_carpooling_car1_idx` (`car_id` ASC) VISIBLE,
  CONSTRAINT `fk_carpooling_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`car` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_has_carpooling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_has_carpooling` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_has_carpooling` (
  `user_user_id` INT NOT NULL,
  `carpooling_carpooling_id` INT NOT NULL,
  PRIMARY KEY (`user_user_id`, `carpooling_carpooling_id`),
  INDEX `fk_user_has_carpooling_carpooling1_idx` (`carpooling_carpooling_id` ASC) VISIBLE,
  INDEX `fk_user_has_carpooling_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_carpooling_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_carpooling_carpooling1`
    FOREIGN KEY (`carpooling_carpooling_id`)
    REFERENCES `mydb`.`carpooling` (`carpooling_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(50) NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`configuration` ;

CREATE TABLE IF NOT EXISTS `mydb`.`configuration` (
  `configuration_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`configuration_id`),
  INDEX `fk_configuration_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_configuration_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parameter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parameter` (
  `parameter_id` INT NOT NULL AUTO_INCREMENT,
  `configuration_id` INT NOT NULL,
  PRIMARY KEY (`parameter_id`),
  INDEX `fk_parameter_configuration1_idx` (`configuration_id` ASC) VISIBLE,
  CONSTRAINT `fk_parameter_configuration1`
    FOREIGN KEY (`configuration_id`)
    REFERENCES `mydb`.`configuration` (`configuration_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
